{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_cpu_usage_percentage{job!=\"prometheus\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(nodejs_heap_size_total_bytes/ nodejs_heap_size_used_bytes) *10",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(http_request_duration_ms_sum{job!=\"prometheus\", route!='/metrics'}[$__range]) / rate(http_request_duration_ms_count{job!=\"prometheus\", route!='/metrics'}[$__range])) by (route, method)",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Number of requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{job!=\"prometheus\", route!=\"/metrics\"}[1m])) by (job)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Number of failed requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{job!=\"prometheus\", status_code=~\"4.*\", route!=\"/metrics\"}[1m])) ",
     "legendFormat": "4xx errors"
    },
    {
     "expr": "sum(increase(http_request_duration_ms_count{job!=\"prometheus\", status_code=~\"5.*\", route!=\"/metrics\"}[1m]))",
     "legendFormat": "5xx errors"
    }
   ]
  },
  {
   "title": "Requests details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{job!=\"prometheus\", status_code=~\"2.*\", route!=\"/metrics\"}[1m])) by (route, method)",
     "legendFormat": "2xx {{method}} {{route}}"
    },
    {
     "expr": "sum(increase(http_request_duration_ms_count{job!=\"prometheus\", status_code=~\"4.*\", route!=\"/metrics\"}[1m])) by (route, method)",
     "legendFormat": "4xx {{method}} {{route}}"
    },
    {
     "expr": "sum(increase(http_request_duration_ms_count{job!=\"prometheus\", status_code=~\"5.*\", route!=\"/metrics\"}[1m])) by (route, method)",
     "legendFormat": "5xx {{method}} {{route}}"
    }
   ]
  }
 ]
}