global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "order-service"
    scrape_interval: 5s
    static_configs:
      - targets: ["docker.for.mac.host.internal:4041"]
  - job_name: "inventory-service"
    scrape_interval: 5s
    static_configs:
      - targets: ["docker.for.mac.host.internal:4042"]
  - job_name: "order-tracking-service"
    scrape_interval: 5s
    static_configs:
      - targets: ["docker.for.mac.host.internal:4043"]
  - job_name: "payment-service"
    scrape_interval: 5s
    static_configs:
      - targets: ["docker.for.mac.host.internal:4044"]
