# apiVersion: 1

# datasources:
#   - name: Prometheus
#     type: prometheus
#     access: proxy
#     url: http://docker.for.mac.host.internal:9090

datasources:
  - name: "prometheus-monitoring-1"
    type: "prometheus"
    access: "proxy"
    org_id: 1
    url: "http://prometheus:9090"
    is_default: true
    version: 1
    editable: true
